format = """
$aws\
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$gcloud \
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$golang\
$helm\
$nodejs\
$python\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$memory_usage\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = '⛅'
style = "bold blue"
[aws.region_aliases]
eu-central-1 = "fr-euc1"
eu-west-1 = "ir-euw1"
us-east-1 = "va-use1"

[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "
full_symbol = "🔋 "
[[battery.display]]
style = "bold red"
threshold = 15

[character]
error_symbol = "[✗](bold red) "
success_symbol = "[➜](bold green) "

[container]
format = "[$symbol \\[$name\\]]($style) "

[git_branch]
symbol = "🌱 "
truncation_length = 11
truncation_symbol = ""
[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
[git_state]
cherry_pick = "[🍒 PICKING](bold red)"
format = '[\($state( $progress_current of $progress_total)\)]($style) '
[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[hostname]
disabled = false
ssh_only = true
ssh_symbol = '🌏 '
trim_at = ''
format = '[$ssh_symbol](bold blue) on [$hostname](bold red)'
style	= 'bold dimmed green'

[kubernetes]
disabled = false
format = '|[🚢 $context \($namespace\)](dimmed green) '
# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

[memory_usage]
disabled = false
format = "$symbol [${ram_pct}]($style) "
style = "bold dimmed green"
symbol = "🐏"
threshold = 75

[line_break]
disabled = false

[nodejs]
format = "via [🧶 $version](bold green) "

[status]
style = 'bg:blue'
symbol = '🔴 '
success_symbol = '🟢 SUCCESS'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = true

[time]
disabled = false
format = '🕒[\[$time\]]($style) '
use_12hr = true
time_format = '%R'
# utc_time_offset = 'local'
utc_time_offset = '+2'
# time_range = '10:00:00-14:00:00'
time_range = '-'

# ~/.config/starship.toml

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
[gcloud.project_aliases]
very-long-project-name = 'vlpn'
