---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: myapp
    deploy: green
  type: ClusterIP
...
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: kube-system
spec:
  type: ExternalName
  externalName: myapp.default.svc.cluster.local
...
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp
            port: 
              number: 80
...
