apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: k8s.gcr.io/busybox
        command: [ "sh", "-c"]
        args: ["printenv MY_PW"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
          - name: MY_PW
            valueFrom:
              secretKeyRef:
                name: secret-name
                key: foo
