apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-name
  namespace: default
spec:
  encryptedData:
    foo: AgAuyy5GfYjAvPsIRz0MwxW12tEj0jjtCRZO/qciIbNVrYfF3cL12utMOhY5StN3W5vrnzCEB8Krf2B7i9+lhDBeW4YC1IS6OxqfocWkLb6ap6fx0gibDag2COJG08AXSrZBUz05amyyMF7enfzRFKM0VnDm9/t+J/e0DSlbl2qOS3h7EkP6Dg4F9p7ih8tzhvgTgTePpPYwP6Va7qJmxGW95gWlMv4+gKBJJtNGzhv24V8z+Xv/9ZA3h1p7N9CJOBHQCJvSx/a8se9xfBxeUJZsuSG9/Xjg5amiIMgnbtlySyp1/Qi/BM9BYNuXhQxlhUHkinN6TPV0Wjz38Z6pQHUe0gOt3AAb5DSvdh0auLzf/oZuUTp6OUAsCTYi4C89ZzDgfdsv7+EtFMXCpsbKVyW4PHLOWNtnz93ilNLJh7YeUOASHet9O+h7eCdxsN+sEWqG8TfgUL8+wtct9qUn0XFPB4ASE3mQQz9GNkOX5fJFR8Rv7FPmMINQSefJdHTHeVjXIBEvghhSWs6u6jHUZmev64fJh7dD2/z3WtwI8ZiEr2I7F2JJn2uuIoggIECgSAIN7r5LjbEY53jAPlDwMK1VU6iCcW5a/Kuunj4n+PPOHOr+7y3+codZdnrSFa9z8CN8VRnT4LLGoM1SRQa/tJkdn9G/4RGFazLbV5xggsUYfmlzbjIuyBwaFvCZA2E3Ei9CSF4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-name
      namespace: default
