# ref: https://github.com/cetic/helm-zabbix/blob/master/values.yaml
zabbixserver:
  image:
    repository: zabbix  # minikube registry
    tag: ubuntu-5.4.5
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/minikube/values.yaml
  extraEnv: {}
