---

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karma-git/DevOps-Playground.git
    targetRevision: master
    path: ./k8s/playground/6.argo-cd/1.raw-or-helm/blue-raw
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
