---

- name: Установка Homebrew пакетов
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_formulae_install_list }}"
  when: "item not in brew_formulae_exclude_list"
