---
# tasks file for macos-env

- import_tasks: debug.yml
# TODO: add conditions, like DEBUG = true

- import_tasks: brew-formulae.yml
  when: brew_formulae_task_enabled

- import_tasks: brew-casks.yml
  when: brew_cask_task_enabled

- import_tasks: pip-packages.yml
  when: pip_task_enabled

- import_tasks: dotfiles-cfgs.yml
  when: dotfiles_task_enabled

- import_tasks: cron.yml
  when: cron_task_enabled
