---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: blue
spec:
  selector:
    matchLabels:
      app: nginx-blue
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      volumes:
        - name: nginx-blue-config
          configMap:
            name: nginx-blue-config
      containers:
      - name: nginx-blue
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-blue-config
