---

name: Get helm values from argo Application
command: |
  helmValues=$(yq e '.spec.source.helm.values' {{path}})
tags:
  - kubernetes
  - helm
  - argo
  - karma
description: Get helm values from argo Application
arguments:
  - name: path
    description: path to argo Application manifest
    default_value: ~
source_url: https://github.com/karma-git/infra/dotfiles
author: karma
author_url: https://github.com/karma-git
shells: []
