---
# https://github.com/gantsign/ansible_role_antigen

users:
  - username: vagrant
    antigen_libraries:
      - name: oh-my-zsh
        env:
          DISABLE_AUTO_UPDATE: '"true"'

    antigen_theme:
      # https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#aussiegeek
      name: aussiegeek
    antigen_bundles:            
      - name: git
      - name: zsh-autosuggestions
        url: zsh-users/zsh-autosuggestions
      - name: zsh-syntax-highlighting
        url: zsh-users/zsh-syntax-highlighting
      - name: docker
      - name: docker-compose
