---
# defaults file for macos-env


# ref: https://brew.sh/; `brew help`
brew:
  # formulae is a regular open source package
  formulae_task_enabled: true
  formulae_install_list:
    - jwt-cli
    - helm
  formulae_exclude_list: []
  # cask is a installation of gui application
  cask_task_enabled: true
  cask_install_list:
    - discord
    - lens
  cask_exclude_list: []

pip:
  task_enabled: true
  install_list:
    # linters
    - ansible-lint
    - black
    - yamllint
  exclude_list: []

dotfiles:
  task_enabled: true