---

apiVersion: v1
kind: Service
metadata:
  name: trivy
  namespace: trivy
spec:
  selector:
    app: trivy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy
  namespace: trivy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:

      containers:
        - name: trivy
          image: karmawow/monorepo-trivy:1.0
          args: ["server"]

          env:
            - name: TRIVY_LISTEN
              value: "0.0.0.0:8080"

            - name: TRIVY_CACHE_BACKEND
              value: "redis://redis:6379"

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"

          ports:
            - containerPort: 8080
