---
# vars file for macos-env

kb_ansible_git_root: /tmp/karma-git-kb
kb_local_root: "/Users/{{ macos_user }}/work/kb/public"

# Используем файлы в удаленной репе или в локальной
dotfiles_path: "{{ kb_ansible_git_root if dotfiles_remote else kb_local_root }}/dotfiles"
