---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appConfig.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appConfig.name }}
spec:
  replicas: {{ .Values.appConfig.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appConfig.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appConfig.name }}
    spec:
      containers:
        - name: {{ .Values.appConfig.name }}
          # yamllint disable rule:line-length
          image: "{{ .Values.appConfig.imageRepository }}:{{ .Values.appConfig.imageVersion }}"
          # yamllint enable rule:line-length
          ports:
            - name: web
              containerPort: 9000
{{- if .Values.env }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
{{- end}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
