---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appConfig.name }}
  # Change this to the namespace the Prometheus instance is running in
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appConfig.name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.appConfig.name }}
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
