---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appConfig.name }}
  name: {{ .Values.appConfig.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{ .Values.appConfig.name }}
