---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fa
  name: fa-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fa
  template:
    metadata:
      labels:
        app: fa
    spec:
      containers:
        - image: karmawow/fastapi:v0.20
          name: fa
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fa-svc
  labels:
    app: fa
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
  selector:
    app: fa
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fa-ing
  annotations:
    # Disables http redirect to https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: fa-svc
              servicePort: 80
