---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: generic-app
  template:
    metadata:
      labels:
        app: generic-app
    spec:
      containers:
        - name: generic-app
          image: nginx
          ports:
            - containerPort: 80
