---

apiVersion: v1
kind: Pod
metadata:
  name: ahorbach-debug-docker
  namespace: kube-system
  labels:
    app: ahorbach-debug-docker
spec:
  # serviceAccountName: my-sa
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: docker-sock
      hostPath:
        path: "/var/run/docker.sock"
        type: Socket
    - name: docker-directory
      hostPath:
        path: "/var/lib/docker"
  containers:
  - command:
    - sleep
    - infinity
    image: docker.io/karmawow/monorepo-devops-tools:2.0
    name: ahorbach-debug-docker
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: "/var/lib/docker"
          name: docker-directory
          readOnly: false
