---

- name: install devops
  hosts: 127.0.0.1
  connection: local
  vars:
    linux_user: aa  # NOTE: your $(whoami)
  
  become: true
  become_method: sudo
  roles:
    - role: devops-env
    - role: devops-env-gui
