---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  selector:
    app: pg
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: pg
        image: postgres:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        env:
          - name: PGDATABASE
            value: postgres
          - name: PGUSER
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: POSTGRES_PASSWORD
        # probes
        readinessProbe:
          exec:
            command: ["psql", "-c", "SELECT 1"]
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["psql", "-c", "SELECT 1"]
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 45
        startupProbe:
          exec:
            command: ["psql", "-c", "SELECT 1"]
          failureThreshold: 10
          periodSeconds: 10
        ports:
        - containerPort: 5432
