---

version: '3.8'

services:

  mkdocs:
    container_name: mkdocs
    build: ./
    command: ["mkdocs", "serve", "--dev-addr", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
