---
version: "2.1"
services:
  code-server:
    # image: lscr.io/linuxserver/code-server
    image: karmawow/code-server
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: code-server
    environment:
      - PUID=10001
      - PGID=10001
      - TZ=Europe/Moscow
      - PASSWORD=codeserverpw
      - SUDO_PASSWORD=codeserverpw
      # ref: https://github.com/coder/code-server/blob/main/docs/FAQ.md#can-i-store-my-password-hashed
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
